# Generated by Django 5.1.5 on 2025-02-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
