# Generated by Django 5.1.5 on 2025-02-04 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_income_user_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
