# Generated by Django 5.1.5 on 2025-02-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0006_alter_adultmodel_image'),
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmodel',
            name='taneoya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taneoya', to='adult.adultmodel'),
        ),
    ]
