# Generated by Django 5.1.5 on 2025-02-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0006_alter_adultmodel_image'),
        ('child', '0002_childmodel_taneoya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmodel',
            name='taneoya',
        ),
        migrations.AddField(
            model_name='childmodel',
            name='taneoya_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adult', to='adult.adultmodel'),
        ),
    ]
