# Generated by Django 5.1.5 on 2025-02-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_remove_childmodel_taneoya_childmodel_taneoya_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmodel',
            name='taneoya_data',
        ),
    ]
